const mongoose = require('mongoose');
const Mixed = mongoose.Schema.Types.Mixed;

const activitySchema = new mongoose.Schema({
    strava_id: { type: Number, required: true, unique: true },
    user_id: { type: mongoose.Schema.Types.Mixed, required: true },
    user_slug: { type: String, required: true, index: true },
    external_id: { type: String },
    upload_id: { type: Number },
    athlete_strava_id: { type: Number },
    athlete_resource_state: { type: Number },
    name: { type: String, required: true },
    type: { type: String, index: true },
    sport_type: { type: String },
    start_date: { type: Date, index: true },
    start_date_local: { type: String },
    timezone: { type: String },
    utc_offset: { type: Number },
    distance: { type: Number, default: 0 },
    elapsed_time: { type: Number, default: 0 },
    moving_time: { type: Number, default: 0 },
    achievement_count: { type: Number },
    kudos_count: { type: Number },
    comment_count: { type: Number },
    athlete_count: { type: Number },
    photo_count: { type: Number },
    average_speed: { type: Number, default: 0 },
    max_speed: { type: Number, default: 0 },
    average_heartrate: { type: Number },
    max_heartrate: { type: Number },
    elev_high: { type: Number },
    elev_low: { type: Number },
    total_elevation_gain: { type: Number, default: 0 },
    pr_count: { type: Number },
    workout_type: { type: Number },
    average_temp: { type: Number },
    average_cadence: { type: Number },
    average_watts: { type: Number },
    weighted_average_watts: { type: Number },
    device_watts: { type: Boolean },
    has_heartrate: { type: Boolean },
    max_watts: { type: Number },
    kilojoules: { type: Number },
    suffer_score: { type: Number },
    description: { type: String },
    calories: { type: Number },
    total_photo_count: { type: Number },
    from_accepted_tag: { type: Boolean },
    device_name: { type: String },
    hide_from_home: { type: Boolean },
    location_city: { type: String },
    location_state: { type: String },
    location_country: { type: String },
    start_latlng: { type: [Number], default: void 0 },
    end_latlng: { type: [Number], default: void 0 },
    summary_polyline: { type: String },
    map_id: { type: String },
    map_polyline: { type: String },
    map_resource_state: { type: Number },
    map_summary_polyline: { type: String },
    map_city: { type: String },
    map_state: { type: String },
    map_country: { type: String },
    line_color: { type: String },
    line_thickness: { type: Number },
    line_opacity: { type: Number },
    segment_efforts: { type: [Mixed], default: void 0 },
    laps: { type: [Mixed], default: void 0 },
    splits_metric: { type: [Mixed], default: void 0 },
    splits_standard: { type: [Mixed], default: void 0 },
    best_efforts: { type: [Mixed], default: void 0 },
    detail_fetched_at: { type: Date },
    stream_resolution: { type: String },
    stream_series_type: { type: String },
    stream_latlng: { type: [[Number]], default: void 0 },
    stream_velocity_smooth: { type: [Number], default: void 0 },
    stream_time: { type: [Number], default: void 0 },
    stream_fetched_at: { type: Date }
}, { timestamps: true });

activitySchema.index({ user_id: 1, type: 1 });
activitySchema.index({ user_id: 1, start_date: 1 });
activitySchema.index({ type: 1, start_date: 1 });
activitySchema.index({ user_slug: 1, start_date: -1 });

module.exports = function getActivityModel() {
    return mongoose.models.Activity || mongoose.model('Activity', activitySchema);
};
