const mongoose = require('mongoose');
const Mixed = mongoose.Schema.Types.Mixed;

const intervalsActivitySchema = new mongoose.Schema({
    schema_version: { type: Number, default: 1 },
    activity_key: { type: String, required: true, index: true },
    intervals_activity_id: { type: String, required: true },
    id: { type: String, required: true },
    user_id: { type: Mixed, required: true },
    user_slug: { type: String, required: true, index: true },
    provider: { type: String, default: 'intervals_icu' },
    provider_athlete_id: { type: String },
    upstream_source: { type: String },
    external_id: { type: String },
    name: { type: String, required: true },
    description: { type: String },
    type: { type: String, index: true },
    sport_type: { type: String },
    sub_type: { type: String },
    activity_type_key: { type: String, index: true },
    activity_type_override: { type: String, index: true },
    activity_type_override_label: { type: String },
    workout_category: { type: String },
    start_date: { type: Date, index: true },
    start_date_local: { type: String },
    timezone: { type: String },
    distance: { type: Number, default: 0 },
    elapsed_time: { type: Number, default: 0 },
    moving_time: { type: Number, default: 0 },
    total_elevation_gain: { type: Number, default: 0 },
    total_elevation_loss: { type: Number },
    average_speed: { type: Number, default: 0 },
    max_speed: { type: Number, default: 0 },
    average_heartrate: { type: Number },
    max_heartrate: { type: Number },
    average_cadence: { type: Number },
    average_watts: { type: Number },
    weighted_average_watts: { type: Number },
    max_watts: { type: Number },
    device_watts: { type: Boolean },
    has_heartrate: { type: Boolean },
    calories: { type: Number },
    average_temp: { type: Number },
    device_name: { type: String },
    trainer: { type: Boolean },
    commute: { type: Boolean },
    race: { type: Boolean },
    perceived_exertion: { type: Number },
    start_latlng: { type: [Number], default: void 0 },
    end_latlng: { type: [Number], default: void 0 },
    stream_latlng: { type: [[Number]], default: void 0 },
    stream_velocity_smooth: { type: [Number], default: void 0 },
    stream_time: { type: [Number], default: void 0 },
    stream_data: { type: Mixed },
    stream_keys: { type: [String], default: void 0 },
    stream_requested_keys: { type: [String], default: void 0 },
    stream_metadata: { type: Mixed },
    stream_resolution: { type: String },
    stream_series_type: { type: String },
    stream_fetched_at: { type: Date },
    map_fetched_at: { type: Date },
    detail_fetched_at: { type: Date },
    intervals: { type: [Mixed], default: void 0 },
    intervals_metrics: { type: Mixed },
    line_color: { type: String },
    line_thickness: { type: Number },
    line_opacity: { type: Number },
    animation_speed_multiplier: { type: Number },
    location_city: { type: String },
    location_state: { type: String },
    location_country: { type: String },
    last_synced_at: { type: Date }
}, { timestamps: true, collection: 'intervals_activities' });

intervalsActivitySchema.index({ user_slug: 1, intervals_activity_id: 1 }, { unique: true });
intervalsActivitySchema.index({ user_slug: 1, activity_key: 1 }, { unique: true });
intervalsActivitySchema.index({ user_slug: 1, start_date: -1 });

module.exports = function getIntervalsActivityModel() {
    return mongoose.models.IntervalsActivity || mongoose.model('IntervalsActivity', intervalsActivitySchema);
};
